### PR TITLE
Updated with some Nomad 0.5 constructs.

### PR DESCRIPTION
**Pull request by donovanmuller**
Added the following:

* [`EphemeralDisk`](https://www.nomadproject.io/docs/job-specification/ephemeral_disk.html)
* [`volumes` ](https://www.nomadproject.io/docs/drivers/docker.html#volumes)
* Missing Java driver fields - like [`jar_path`](https://www.nomadproject.io/docs/drivers/java.html#jar_path) and [`jvm_options`](https://www.nomadproject.io/docs/drivers/java.html#jvm_options)
* [`Artifacts`]( https://www.nomadproject.io/docs/job-specification/artifact.html)

Also added `@Builder` to `Task` and `Task.Config`, allowing easier creation of these
constructs when dealing with optional values.

### CODE REVIEW

**Comment by zanella** [comment]
@donovanmuller maybe it's better to wait a while before bumping the version on maven central ? Do you have more PRs at work ?

**Comment by donovanmuller** [comment]
@zanella no, these are all the changes I need right now. I'd really appreciate a `0.4` release as the next release of https://github.com/donovanmuller/spring-cloud-deployer-nomad depends on these changes.

**Comment by donovanmuller** [comment]
@zanella thanks for write access 👍.
Not sure what the process is to push to central but if it's possible and you agree to grant me access somehow, I'm more than willing to help out with releasing etc.

**Comment by zanella** [comment]
@donovanmuller uploaded 0.4, should be in central soon.

I'll let you know about the releasing later on when I read up how it works w/ multiple people, cheers

**Comment by donovanmuller** [comment]
@zanella Thanks! Really appreciate it.

**Pull request merged**
