### PR TITLE
Added missing fields to NodeInfo

### PR DESCRIPTION
**Pull request by vicmosin**

### CODE REVIEW

**Comment by zanella** [comment]
LGTM, could you just please rebase it?

**Comment by vicmosin** [comment]
@zanella I am sorry, I tried it already.. Can you maybe point me to some manual how exactly to do that? I added remote to this repo, and then did rebase this repo..

**Comment by zanella** [comment]
Seems like when you merged the commits got duplicated:

- https://github.com/smoope/nomad-api/commit/79a0285624e3f64dae11190e96f44a2d448de827
- https://github.com/smoope/nomad-api/commit/a1fe3b5f59f13049d430af20a555d11be517370e

Probably you merged the branches without rebasing the second one that was commited, you can `rebase -i HEAD~3` your master branch and remove `a1fe3b5` (dup) and `fe95cee` (merge commit, useless).

Since it's the master branch you'll probably need to `push --force` after the rebase.

Let me know if I was not too helpful on my explanation.

**Comment by vicmosin** [comment]
@zanella I guess that's it, or?

**Comment by vicmosin** [comment]
@zanella thanks for explanation))

**Comment by zanella** [comment]
@donovanmuller feel free to merge

**Pull request merged**
