### PR TITLE
Added missing CreateTime field

### PR DESCRIPTION
**Pull request by vicmosin**
Not described in docs. All time-based values are used with nanoseconds. So in order to convert them to DateTime you'll have to devide them by 100 and then convert timestamp to Date.

### CODE REVIEW

**Comment by vicmosin** [comment]
@zanella which java version do you use? Can't compile with LocalDateTime..

**Comment by zanella** [comment]
Java 8, I'll take a look later on.

**Comment by donovanmuller** [comment]
@vicmosin The [default Travis JDK](https://docs.travis-ci.com/user/languages/java#Overview) is Oracle JDK **7**, hence the compilation errors.

See [this gist](https://gist.github.com/donovanmuller/84cc3544b9a9353eea69fcb39db42486) for the changes required to move the project to Java 8 (also includes Travis change).

@zanella any reason you would not want the project to compile and target Java 8?

**Comment by zanella** [comment]
@donovanmuller I guess I tried to be not so "edgy" and stick to 7, since 8 is the "new thing", just forgot to document it, heh, but doesn't seem to make a whole lot of sense, given that nomad is so new, and probably whoever uses it will be able to use 8, unless it's some stringent corporate setup...

**Comment by donovanmuller** [comment]
@zanella Considering Java 7 is [EOL](http://www.oracle.com/technetwork/java/eol-135779.html and as you mentioned, Nomad is rather cutting edge itself, I don't see any reason not too use Java 8.

**Comment by zanella** [comment]
@donovanmuller, yeah, indeed, +1 to going to 8, maybe just making it clear in the README that it is 8+

About the PR itself: LGTM, though I don't have a working nomad to test, so I think you're better than me to judge it @donovanmuller 

@vicmosin Can you please push the changes on the gist (going to JDK 8) ?

**Comment by donovanmuller** [comment]
@zanella @vicmosin Few things from my side:

* I'm not so sure the `LocalDateTime` conversion is something that should be done in this project. I mean, what if a consumer relies on the nanosecond precision (as returned by Nomad) for date/time based fields?
* The system default timezone is used (`ZoneId.systemDefault()`) but is that a safe assumption for all use cases? What if you have a Nomad environment using a different timezone than the system that the consumer is making the call from but want the timezone to match that of the cluster?
* There are many other references to time/date fields ([`Service.Check#timeout`](https://github.com/zanella/nomad-api/blob/master/src/main/java/io/github/zanella/nomad/v1/nodes/models/Service.java#L19), [`TaskGroup.RestartPolicy#delay`](https://github.com/zanella/nomad-api/blob/master/src/main/java/io/github/zanella/nomad/v1/nodes/models/TaskGroup.java#L21), etc.), so these fields would have to be updated to be consistent with the field changed in this PR.

However, as per my first two points, I don't believe this sort of explicit conversion is something this project should handle. Given the sometimes complex requirements around date/time conversion, I think that is something the application should rather handle itself. I.e. leave the time fields as `Long`, representing nanosecond times. Perhaps document this fact?

@vicmosin Thoughts?

**Comment by zanella** [comment]
Indeed, I was leaning towards the "convenience" side of showing reasonable conversion as well, but @donovanmuller is right, date conversion is always thorny

**Comment by vicmosin** [comment]
@zanella done, could you please resolve the conflict in pom?

**Comment by vicmosin** [comment]
Please release.. ))

**Comment by donovanmuller** [comment]
@zanella will have to assist when he has some time.

**Comment by zanella** [comment]
Released, 0.6

**Pull request merged**
